name: GitHub Actions Build and Deploy
on:
  push:
    branches:
      - master
jobs:
  build-and-deploy:
    runs-on: ubuntu-latest
    steps:
    - name: Checkout
      uses: actions/checkout

    - name: Build and Deploy
      uses: JamesIves/github-pages-deploy-action@v4.4.3
      env:
        BRANCH: gh-pages
        FOLDER: dist
        BUILD_SCRIPT: cd frontend && npm install && npm run production
